version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_install:
      - git clone https://github.com/paleolimbot/s2geography
      - |
        cmake -S s2geography -B s2geography/build -DS2GEOGRAPHY_S2_SOURCE=CONDA -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/docs/checkouts/readthedocs.org/user_builds/spherely/conda/$READTHEDOCS_VERSION -DCMAKE_INSTALL_LIBDIR=/home/docs/checkouts/readthedocs.org/user_builds/spherely/conda/$READTHEDOCS_VERSION/lib
      - cmake --build s2geography/build
      - cmake --install s2geography/build

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .

formats: []
