
name: spherely-docs
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - cxx-compiler
  - cmake
  - make
  - s2geometry>=0.11.1
  - s2geography>=0.2.0
  - libabseil
  - sphinx
  - pydata-sphinx-theme=0.15.4
  - sphinx-book-theme=1.1.3
  - myst-nb
  - pip
  # TODO: install the library here when s2geography is packaged
  #- pip:
  #  - ..
