
name: spherely-docs
channels:
  - conda-forge
dependencies:
  - numpy
  - cxx-compiler
  - cmake
  - make
  - s2geometry
  - libabseil
  - sphinx
  - sphinx-book-theme
  - myst-nb
  - pip
  # TODO: install the library here when s2geography is packaged
  #- pip:
  #  - ..
