on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Lint

jobs:
  lint:
    name: mypy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup micromamba
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-file: ci/environment.yml
          environment-name: spherely-dev
          extra-specs: |
            python=3.11

      - name: Build and install spherely
        run: |
          python -m pip install . -v --no-build-isolation

      - name: Install mypy
        run: |
          python -m pip install 'mypy<0.990'

      - name: Run mypy
        run: |
          python -m mypy --install-types --non-interactive
